---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
  inventory:
    group_vars:
      all:
        project_dir: ${MOLECULE_PROJECT_DIRECTORY}
        frigate_docker_container_network: foo
        frigate_docker_ports:
          web_ui:
            expose: true
            port: 8971
          web_ui_unauth:
            expose: false
            port: 5000
          rtsp:
            expose: false
            port: 8554
          webrtc_tcp:
            expose: true
            port: 8555
          webrtc_udp:
            expose: true
            port: 8555
