---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/docker
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

ansible:
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
  cfg:
    defaults:
      callbacks_enabled: profile_tasks
      inject_facts_as_vars: false

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        frigate_docker_storage_use_docker_volume: true

scenario:
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
